export const TORQUE_ROD_BUSH_BOGIE = [
  {
    id: 100001,
    type: "ลูกหมากเพลาโบกี้",
    kind: "TORQUE ROD BUSH",
    name: "bogie-standard",
    image: "/images/products/torque-rod-bush/bogie/standard/standard-1.jpg",
    link: "/products/torque-rod-bush/bogie/standard",
    images: [
      "/images/products/torque-rod-bush/bogie/standard/standard-1.jpg",
      "/images/products/torque-rod-bush/bogie/standard/standard-2.jpg",
      "/images/products/torque-rod-bush/bogie/standard/standard-3.jpg",
    ],
  },
  {
    id: 100002,
    type: "ลูกหมากเพลาโบกี้",
    kind: "TORQUE ROD BUSH",
    name: "bogie-four-holes",
    image: "/images/products/torque-rod-bush/bogie/four-holes/four-holes-1.jpg",
    link: "/products/torque-rod-bush/bogie/four-holes",
    images: [
      "/images/products/torque-rod-bush/bogie/four-holes/four-holes-1.jpg",
      "/images/products/torque-rod-bush/bogie/four-holes/four-holes-2.jpg",
      "/images/products/torque-rod-bush/bogie/four-holes/four-holes-3.jpg",
      "/images/products/torque-rod-bush/bogie/four-holes/four-holes-4.jpg",
    ],
  },
  {
    id: 100003,
    type: "ลูกหมากเพลาโบกี้",
    kind: "TORQUE ROD BUSH",
    name: "bogie-wrapper",
    image: "/images/products/torque-rod-bush/bogie/wrapper/wrapper-1.jpg",
    link: "/products/torque-rod-bush/bogie/wrapper",
    images: [
      "/images/products/torque-rod-bush/bogie/wrapper/wrapper-1.jpg",
      "/images/products/torque-rod-bush/bogie/wrapper/wrapper-2.jpg",
    ],
  },
  {
    id: 100004,
    type: "ลูกหมากเพลาโบกี้",
    kind: "TORQUE ROD BUSH",
    name: "bogie-isuzu",
    image: "/images/products/torque-rod-bush/bogie/isuzu/isuzu-1.jpg",
    link: "/products/torque-rod-bush/bogie/isuzu",
    images: [
      "/images/products/torque-rod-bush/bogie/isuzu/isuzu-1.jpg",
      "/images/products/torque-rod-bush/bogie/isuzu/isuzu-2.jpg",
      "/images/products/torque-rod-bush/bogie/isuzu/isuzu-3.jpg",
      "/images/products/torque-rod-bush/bogie/isuzu/isuzu-4.jpg",
    ],
  },
  {
    id: 100005,
    type: "ลูกหมากเพลาโบกี้",
    kind: "TORQUE ROD BUSH",
    name: "bogie-egypt",
    image: "/images/products/torque-rod-bush/bogie/egypt/egypt-1.jpg",
    link: "/products/torque-rod-bush/bogie/egypt",
    images: [
      "/images/products/torque-rod-bush/bogie/egypt/egypt-1.jpg",
      "/images/products/torque-rod-bush/bogie/egypt/egypt-2.jpg",
      "/images/products/torque-rod-bush/bogie/egypt/egypt-3.jpg",
      "/images/products/torque-rod-bush/bogie/egypt/egypt-4.jpg",
    ],
  },
  {
    id: 100006,
    type: "ลูกหมากเพลาโบกี้",
    kind: "TORQUE ROD BUSH",
    name: "bogie-gx-0",
    image: "/images/products/torque-rod-bush/bogie/gx-0/gx-0-1.jpg",
    link: "/products/torque-rod-bush/bogie/gx-0",
    images: [
      "/images/products/torque-rod-bush/bogie/gx-0/gx-0-1.jpg",
      "/images/products/torque-rod-bush/bogie/gx-0/gx-0-2.jpg",
      "/images/products/torque-rod-bush/bogie/gx-0/gx-0-3.jpg",
      "/images/products/torque-rod-bush/bogie/gx-0/gx-0-4.jpg",
    ],
  },
  {
    id: 100007,
    type: "ลูกหมากเพลาโบกี้",
    kind: "TORQUE ROD BUSH",
    name: "bogie-hino-series",
    image:
      "/images/products/torque-rod-bush/bogie/hino-series/hino-series-1.jpg",
    link: "/products/torque-rod-bush/bogie/hino-series",
    images: [
      "/images/products/torque-rod-bush/bogie/hino-series/hino-series-1.jpg",
      "/images/products/torque-rod-bush/bogie/hino-series/hino-series-2.jpg",
      "/images/products/torque-rod-bush/bogie/hino-series/hino-series-3.jpg",
      "/images/products/torque-rod-bush/bogie/hino-series/hino-series-4.jpg",
    ],
  },
  {
    id: 100008,
    type: "ลูกหมากเพลาโบกี้",
    kind: "TORQUE ROD BUSH",
    name: "bogie-lg-mg-mt",
    image: "/images/products/torque-rod-bush/bogie/lg-mg-mt/lg-mg-mt-1.jpg",
    link: "/products/torque-rod-bush/bogie/lg-mg-mt",
    images: [
      "/images/products/torque-rod-bush/bogie/lg-mg-mt/lg-mg-mt-1.jpg",
      "/images/products/torque-rod-bush/bogie/lg-mg-mt/lg-mg-mt-2.jpg",
      "/images/products/torque-rod-bush/bogie/lg-mg-mt/lg-mg-mt-3.jpg",
      "/images/products/torque-rod-bush/bogie/lg-mg-mt/lg-mg-mt-4.jpg",
    ],
  },
  {
    id: 100009,
    type: "ลูกหมากเพลาโบกี้",
    kind: "TORQUE ROD BUSH",
    name: "bogie-p-1",
    image: "/images/products/torque-rod-bush/bogie/p-1/p-1-1.jpg",
    link: "/products/torque-rod-bush/bogie/p-1",
    images: [
      "/images/products/torque-rod-bush/bogie/p-1/p-1-1.jpg",
      "/images/products/torque-rod-bush/bogie/p-1/p-1-2.jpg",
      "/images/products/torque-rod-bush/bogie/p-1/p-1-3.jpg",
    ],
  },
  {
    id: 100010,
    type: "ลูกหมากเพลาโบกี้",
    kind: "TORQUE ROD BUSH",
    name: "bogie-p-2",
    image: "/images/products/torque-rod-bush/bogie/p-2/p-2-1.jpg",
    link: "/products/torque-rod-bush/bogie/p-2",
    images: [
      "/images/products/torque-rod-bush/bogie/p-2/p-2-1.jpg",
      "/images/products/torque-rod-bush/bogie/p-2/p-2-2.jpg",
      "/images/products/torque-rod-bush/bogie/p-2/p-2-3.jpg",
    ],
  },
  {
    id: 100011,
    type: "ลูกหมากเพลาโบกี้",
    kind: "TORQUE ROD BUSH",
    name: "bogie-p-3",
    image: "/images/products/torque-rod-bush/bogie/p-3/p-3-1.jpg",
    link: "/products/torque-rod-bush/bogie/p-3",
    images: [
      "/images/products/torque-rod-bush/bogie/p-3/p-3-1.jpg",
      "/images/products/torque-rod-bush/bogie/p-3/p-3-2.jpg",
      "/images/products/torque-rod-bush/bogie/p-3/p-3-3.jpg",
    ],
  },
  {
    id: 100012,
    type: "ลูกหมากเพลาโบกี้",
    kind: "TORQUE ROD BUSH",
    name: "bogie-p.a.inter",
    image: "/images/products/torque-rod-bush/bogie/p.a.inter/p.a.inter-1.jpg",
    link: "/products/torque-rod-bush/bogie/p.a.inter",
    images: [
      "/images/products/torque-rod-bush/bogie/p.a.inter/p.a.inter-1.jpg",
      "/images/products/torque-rod-bush/bogie/p.a.inter/p.a.inter-2.jpg",
      "/images/products/torque-rod-bush/bogie/p.a.inter/p.a.inter-3.jpg",
    ],
  },
  {
    id: 100013,
    type: "ลูกหมากเพลาโบกี้",
    kind: "TORQUE ROD BUSH",
    name: "bogie-py",
    image: "/images/products/torque-rod-bush/bogie/py/py-1.jpg",
    link: "/products/torque-rod-bush/bogie/py",
    images: [
      "/images/products/torque-rod-bush/bogie/py/py-1.jpg",
      "/images/products/torque-rod-bush/bogie/py/py-2.jpg",
      "/images/products/torque-rod-bush/bogie/py/py-3.jpg",
      "/images/products/torque-rod-bush/bogie/py/py-4.jpg",
    ],
  },
  {
    id: 100014,
    type: "ลูกหมากเพลาโบกี้",
    kind: "TORQUE ROD BUSH",
    name: "bogie-sunny",
    image: "/images/products/torque-rod-bush/bogie/sunny/sunny-1.jpg",
    link: "/products/torque-rod-bush/bogie/sunny",
    images: [
      "/images/products/torque-rod-bush/bogie/sunny/sunny-1.jpg",
      "/images/products/torque-rod-bush/bogie/sunny/sunny-2.jpg",
      "/images/products/torque-rod-bush/bogie/sunny/sunny-3.jpg",
      "/images/products/torque-rod-bush/bogie/sunny/sunny-4.jpg",
    ],
  },
  {
    id: 100015,
    type: "ลูกหมากเพลาโบกี้",
    kind: "TORQUE ROD BUSH",
    name: "bogie-super-black-core",
    image:
      "/images/products/torque-rod-bush/bogie/super-black-core/super-black-core-1.jpg",
    link: "/products/torque-rod-bush/bogie/super-black-core",
    images: [
      "/images/products/torque-rod-bush/bogie/super-black-core/super-black-core-1.jpg",
      "/images/products/torque-rod-bush/bogie/super-black-core/super-black-core-2.jpg",
      "/images/products/torque-rod-bush/bogie/super-black-core/super-black-core-3.jpg",
    ],
  },
  {
    id: 100016,
    type: "ลูกหมากเพลาโบกี้",
    kind: "TORQUE ROD BUSH",
    name: "bogie-super-open-core",
    image:
      "/images/products/torque-rod-bush/bogie/super-open-core/super-open-core-1.jpg",
    link: "/products/torque-rod-bush/bogie/super-open-core",
    images: [
      "/images/products/torque-rod-bush/bogie/super-open-core/super-open-core-1.jpg",
      "/images/products/torque-rod-bush/bogie/super-open-core/super-open-core-2.jpg",
    ],
  },
  {
    id: 100017,
    type: "ลูกหมากเพลาโบกี้",
    kind: "TORQUE ROD BUSH",
    name: "bogie-super-small-core",
    image:
      "/images/products/torque-rod-bush/bogie/super-small-core/super-small-core-1.jpg",
    link: "/products/torque-rod-bush/bogie/super-small-core",
    images: [
      "/images/products/torque-rod-bush/bogie/super-small-core/super-small-core-1.jpg",
      "/images/products/torque-rod-bush/bogie/super-small-core/super-small-core-2.jpg",
      "/images/products/torque-rod-bush/bogie/super-small-core/super-small-core-3.jpg",
    ],
  },
  {
    id: 100018,
    type: "ลูกหมากเพลาโบกี้",
    kind: "TORQUE ROD BUSH",
    name: "bogie-super-pyk",
    image: "/images/products/torque-rod-bush/bogie/super-pyk/super-pyk-1.jpg",
    link: "/products/torque-rod-bush/bogie/super-pyk",
    images: [
      "/images/products/torque-rod-bush/bogie/super-pyk/super-pyk-1.jpg",
      "/images/products/torque-rod-bush/bogie/super-pyk/super-pyk-2.jpg",
      "/images/products/torque-rod-bush/bogie/super-pyk/super-pyk-3.jpg",
    ],
  },
  {
    id: 100019,
    type: "ลูกหมากเพลาโบกี้",
    kind: "TORQUE ROD BUSH",
    name: "bogie-super-ud-outer-head",
    image:
      "/images/products/torque-rod-bush/bogie/ud-outer-head/ud-outer-head-1.jpg",
    link: "/products/torque-rod-bush/bogie/ud-outer-head",
    images: [
      "/images/products/torque-rod-bush/bogie/ud-outer-head/ud-outer-head-1.jpg",
      "/images/products/torque-rod-bush/bogie/ud-outer-head/ud-outer-head-2.jpg",
      "/images/products/torque-rod-bush/bogie/ud-outer-head/ud-outer-head-3.jpg",
      "/images/products/torque-rod-bush/bogie/ud-outer-head/ud-outer-head-4.jpg",
      "/images/products/torque-rod-bush/bogie/ud-outer-head/ud-outer-head-5.jpg",
    ],
  },
  {
    id: 100020,
    type: "ลูกหมากเพลาโบกี้",
    kind: "TORQUE ROD BUSH",
    name: "bogie-super-jcm",
    image: "/images/products/torque-rod-bush/bogie/jcm/jcm-1.jpg",
    link: "/products/torque-rod-bush/bogie/jcm",
    images: [
      "/images/products/torque-rod-bush/bogie/jcm/jcm-1.jpg",
      "/images/products/torque-rod-bush/bogie/jcm/jcm-2.jpg",
      "/images/products/torque-rod-bush/bogie/jcm/jcm-3.jpg",
    ],
  },
  {
    id: 100021,
    type: "ลูกหมากเพลาโบกี้",
    kind: "TORQUE ROD BUSH",
    name: "bogie-super-kt",
    image: "/images/products/torque-rod-bush/bogie/kt/kt-1.jpg",
    link: "/products/torque-rod-bush/bogie/kt",
    images: [
      "/images/products/torque-rod-bush/bogie/kt/kt-1.jpg",
      "/images/products/torque-rod-bush/bogie/kt/kt-2.jpg",
      "/images/products/torque-rod-bush/bogie/kt/kt-3.jpg",
    ],
  },
  {
    id: 100021,
    type: "ลูกหมากเพลาโบกี้",
    kind: "TORQUE ROD BUSH",
    name: "bogie-super-tx-68",
    image: "/images/products/torque-rod-bush/bogie/tx-68/tx-68-1.jpg",
    link: "/products/torque-rod-bush/bogie/tx-68",
    images: [
      "/images/products/torque-rod-bush/bogie/tx-68/tx-68-1.jpg",
      "/images/products/torque-rod-bush/bogie/tx-68/tx-68-2.jpg",
      "/images/products/torque-rod-bush/bogie/tx-68/tx-68-3.jpg",
      "/images/products/torque-rod-bush/bogie/tx-68/tx-68-4.jpg",
    ],
  },
  {
    id: 100022,
    type: "ลูกหมากเพลาโบกี้",
    kind: "TORQUE ROD BUSH",
    name: "bogie-super-ud",
    image: "/images/products/torque-rod-bush/bogie/ud/ud-1.jpg",
    link: "/products/torque-rod-bush/bogie/ud",
    images: [
      "/images/products/torque-rod-bush/bogie/ud/ud-1.jpg",
      "/images/products/torque-rod-bush/bogie/ud/ud-2.jpg",
      "/images/products/torque-rod-bush/bogie/ud/ud-3.jpg",
      "/images/products/torque-rod-bush/bogie/ud/ud-4.jpg",
      "/images/products/torque-rod-bush/bogie/ud/ud-5.jpg",
    ],
  },
];

export const TORQUE_ROD_BUSH_SCANIA = [
  {
    id: 200001,
    type: "ลูกหมาก SCANIA",
    kind: "TORQUE ROD BUSH",
    name: "scania-big-hole",
    image: "/images/products/torque-rod-bush/scania/big-hole/big-hole-1.jpg",
    link: "/products/torque-rod-bush/scania/big-hole",
    images: [
      "/images/products/torque-rod-bush/scania/big-hole/big-hole-1.jpg",
      "/images/products/torque-rod-bush/scania/big-hole/big-hole-2.jpg",
      "/images/products/torque-rod-bush/scania/big-hole/big-hole-3.jpg",
      "/images/products/torque-rod-bush/scania/big-hole/big-hole-4.jpg",
    ],
  },
  {
    id: 200002,
    type: "ลูกหมาก SCANIA",
    kind: "TORQUE ROD BUSH",
    name: "scania-small-hole",
    image:
      "/images/products/torque-rod-bush/scania/small-hole/small-hole-1.jpg",
    link: "/products/torque-rod-bush/scania/small-hole",
    images: [
      "/images/products/torque-rod-bush/scania/small-hole/small-hole-1.jpg",
      "/images/products/torque-rod-bush/scania/small-hole/small-hole-2.jpg",
      "/images/products/torque-rod-bush/scania/small-hole/small-hole-3.jpg",
      "/images/products/torque-rod-bush/scania/small-hole/small-hole-4.jpg",
    ],
  },
];

export const TORQUE_ROD_BUSH_CHINESE = [
  {
    id: 300001,
    type: "ลูกหมากรถจีน",
    kind: "TORQUE ROD BUSH",
    name: "chinese-tongfong",
    image: "/images/products/torque-rod-bush/chinese/tongfong/tongfong-1.jpg",
    link: "/products/torque-rod-bush/chinese/tongfong",
    images: [
      "/images/products/torque-rod-bush/chinese/tongfong/tongfong-1.jpg",
      "/images/products/torque-rod-bush/chinese/tongfong/tongfong-2.jpg",
      "/images/products/torque-rod-bush/chinese/tongfong/tongfong-3.jpg",
      "/images/products/torque-rod-bush/chinese/tongfong/tongfong-4.jpg",
    ],
  },
  {
    id: 300002,
    type: "ลูกหมากรถจีน",
    kind: "TORQUE ROD BUSH",
    name: "chinese-faw-small",
    image: "/images/products/torque-rod-bush/chinese/faw-small/faw-small-1.jpg",
    link: "/products/torque-rod-bush/chinese/faw-small",
    images: [
      "/images/products/torque-rod-bush/chinese/faw-small/faw-small-1.jpg",
      "/images/products/torque-rod-bush/chinese/faw-small/faw-small-2.jpg",
      "/images/products/torque-rod-bush/chinese/faw-small/faw-small-3.jpg",
      "/images/products/torque-rod-bush/chinese/faw-small/faw-small-4.jpg",
    ],
  },
  {
    id: 300003,
    type: "ลูกหมากรถจีน",
    kind: "TORQUE ROD BUSH",
    name: "chinese-faw-big",
    image: "/images/products/torque-rod-bush/chinese/faw-big/faw-big-1.jpg",
    link: "/products/torque-rod-bush/chinese/faw-big",
    images: [
      "/images/products/torque-rod-bush/chinese/faw-big/faw-big-1.jpg",
      "/images/products/torque-rod-bush/chinese/faw-big/faw-big-2.jpg",
      "/images/products/torque-rod-bush/chinese/faw-big/faw-big-3.jpg",
      "/images/products/torque-rod-bush/chinese/faw-big/faw-big-4.jpg",
    ],
  },
  {
    id: 300004,
    type: "ลูกหมากรถจีน",
    kind: "TORQUE ROD BUSH",
    name: "chinese-faw-dump",
    image: "/images/products/torque-rod-bush/chinese/faw-dump/faw-dump-1.jpg",
    link: "/products/torque-rod-bush/chinese/faw-dump",
    images: [
      "/images/products/torque-rod-bush/chinese/faw-dump/faw-dump-1.jpg",
      "/images/products/torque-rod-bush/chinese/faw-dump/faw-dump-2.jpg",
      "/images/products/torque-rod-bush/chinese/faw-dump/faw-dump-3.jpg",
      "/images/products/torque-rod-bush/chinese/faw-dump/faw-dump-4.jpg",
    ],
  },
  {
    id: 300005,
    type: "ลูกหมากรถจีน",
    kind: "TORQUE ROD BUSH",
    name: "chinese-pawson",
    image: "/images/products/torque-rod-bush/chinese/pawson/pawson-1.jpg",
    link: "/products/torque-rod-bush/chinese/pawson",
    images: [
      "/images/products/torque-rod-bush/chinese/pawson/pawson-1.jpg",
      "/images/products/torque-rod-bush/chinese/pawson/pawson-2.jpg",
      "/images/products/torque-rod-bush/chinese/pawson/pawson-3.jpg",
      "/images/products/torque-rod-bush/chinese/pawson/pawson-4.jpg",
    ],
  },
];

export const TORQUE_ROD_BUSH_CRANE = [
  {
    id: 400001,
    type: "ลูกหมากรถเครน",
    kind: "TORQUE ROD BUSH",
    name: "crane-tadano",
    image: "/images/products/torque-rod-bush/crane/tadano/tadano-1.jpg",
    link: "/products/torque-rod-bush/crane/tadano",
    images: [
      "/images/products/torque-rod-bush/crane/tadano/tadano-1.jpg",
      "/images/products/torque-rod-bush/crane/tadano/tadano-2.jpg",
      "/images/products/torque-rod-bush/crane/tadano/tadano-3.jpg",
      "/images/products/torque-rod-bush/crane/tadano/tadano-4.jpg",
      "/images/products/torque-rod-bush/crane/tadano/tadano-5.jpg",
    ],
  },
];
